---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: lifecycle-toolkit
  namespace: default
spec:
  interval: 5m
  url: https://github.com/keptn/lifecycle-toolkit
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include deploy dir
    !/examples/podtatohead-deployment
    
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podtatohead
  namespace: default
spec:
  interval: 15m
  path: "./examples/podtatohead-deployment"
  prune: true
  sourceRef:
    kind: GitRepository
    name: lifecycle-toolkit
