apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keptn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # enabling cascading deletion
spec:
  project: default
  source:
    repoURL: 'https://github.com/keptn/lifecycle-toolkit-charts' # repository containing helm charts
    path: charts/keptn # path to helm charts inside repository
    targetRevision: HEAD
    helm:
      parameters:
        - name: "commitID"
          value: "$ARGOCD_APP_REVISION"
  destination:
    server: 'https://kubernetes.default.svc' # server where Keptn will be deployed
    namespace: keptn-system # namespace where Keptn will be deployed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
