## @section Keptn
certManager:
## @param certManager.enabled Enable this value to install Keptn Certificate Manager
  enabled: true
lifecycleOperator:
## @param lifecycleOperator.enabled Enable this value to install Keptn Lifecycle Operator
  enabled: true
metricsOperator:
## @param metricsOperator.enabled Enable this value to install Keptn Metrics Operator
  enabled: true

## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
##

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
## @param global.namespaceOverride Override the namespace for resource deployed by the chart, but can itself be overridden by the local namespaceOverride
##
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  ## @param commonLabels Common annotations to add to all Keptn resources. Evaluated as a template
  ##
  commonLabels: { }
  ## @param commonAnnotations Common annotations to add to all Mongo resources. Evaluated as a template
  ##
  commonAnnotations: { }




