apiVersion: lifecycle.keptn.sh/v1alpha1
kind: KeptnEvaluationDefinition
metadata:
  name: app-pre-deploy-eval-1
  namespace: podtato-kubectl
spec:
  source: prometheus

  objectives:
    - name: available-cpus ## this query should fail
      query: "sum(kube_pod_container_resource_limits{resource='cpu'}) - sum(kube_node_status_capacity{resource='cpu'})"
      evaluationTarget: ">4"
