---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: metrics-validating-webhook-configuration
  labels:
    keptn.sh/inject-cert: "true"
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: metrics-webhook-service
        namespace: system
        path: /validate-metrics-keptn-sh-v1alpha3-keptnmetric
    failurePolicy: Fail
    name: vkeptnmetric.kb.io
    rules:
      - apiGroups:
          - metrics.keptn.sh
        apiVersions:
          - v1alpha3
        operations:
          - CREATE
          - UPDATE
        resources:
          - keptnmetrics
    sideEffects: None
