apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-head-frontend
  namespace: podtato-kubectl
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: podtato-head-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podtato-head-frontend
        app.kubernetes.io/part-of: podtato-head
        app.kubernetes.io/version: 0.1.0 # The version label stays the same and therefore no related KeptnWorkload will be affected
        keptn.sh/pre-deployment-tasks: pre-deployment-check
    spec:
      containers:
        - name: podtato-head-frontend
          image: podtato-head-frontend:b # Only the image tag has been updated from 'a' to 'b'
