[build]
base = "docs/"
publish = "public/"
command = "hugo -b $DEPLOY_PRIME_URL"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../netlify.toml"

[build.environment]
# added specifically a docker image, so the versions within makefile and netlify documentation match
# renovate: datasource=docker depName=klakegg/hugo
HUGO_VERSION = "0.107.0"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
HUGO_ENV = "development"

[context.branch-deploy]
HUGO_ENV = "staging"

[context.production.environment]
HUGO_ENV = "production"

[context.production]
command = "hugo -b $URL"
