# permissions for end users to edit analysisvaluetemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: analysisvaluetemplate-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: metrics-operator
    app.kubernetes.io/part-of: metrics-operator
    app.kubernetes.io/managed-by: kustomize
  name: analysisvaluetemplate-editor-role
rules:
- apiGroups:
  - metrics.keptn.sh
  resources:
  - analysisvaluetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metrics.keptn.sh
  resources:
  - analysisvaluetemplates/status
  verbs:
  - get
