apiVersion: metrics.keptn.sh/v1alpha3
kind: KeptnMetric
metadata:
  labels:
    app.kubernetes.io/name: keptnmetric
    app.kubernetes.io/instance: keptnmetric-sample
    app.kubernetes.io/part-of: metrics-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: metrics-operator
  name: keptnmetric-sample
spec:
# TODO(user): Add fields here
