apiVersion: lifecycle.keptn.sh/v1alpha1
kind: KeptnTask
metadata:
  name: hello-developer-upstream
spec:
  taskDefinition: hello-keptn-upstream
  workload: my-workload
  version: "1.0"
  application: my-app