name: "Deploy Prometheus on GH cluster"
description: "Deploys and exposes Prometheus on GH cluster"
runs:
  using: "composite"
  steps:
    - name: Install and expose Prometheus
      shell: bash
      run: |
        make install-prometheus
        # wait for port 9090 to become available
        while ! nc -vz localhost 9090 > /dev/null 2>&1 ; do
        echo "Sleeping until port-forward for Prometheus at port 9090 is ready..."
        sleep 5
        done
        
        # wait until node exporter is available
        while ! nc -vz localhost 9100 > /dev/null 2>&1 ; do
        echo "Sleeping until port-forward for node exporter at port 9100 is ready..."
        sleep 5
        done
