apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podtato-head-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/<repo-owner>/<repo>'
    path: dev
    targetRevision: main
    helm:
      parameters:
        - name: "commitID"
          value: "$ARGOCD_APP_REVISION"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: podtato-head-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podtato-head-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/<repo-owner>/<repo>'
    path: production
    targetRevision: main
    helm:
      parameters:
        - name: "commitID"
          value: "$ARGOCD_APP_REVISION"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: podtato-head-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
