global:
  certManagerEnabled: false
  imageRegistry: "testreg"
  commonLabels:
    app.kubernetes.io/version: vmyversion

lifecycleOperator:
  enabled: true
  lifecycleOperator:
    image:
      repository: myrep
      tag: v0.0.1
  scheduler:
    image:
      tag: v0.0.0
  deniedNamespaces: ["foo", "bar"]

metricsOperator:
  enabled: false
  imagePullSecrets: []
