global:
  imageRegistry: "testreg"

certManager:
  enabled: false
lifecycleOperator:
  enabled: true
  lifecycleOperator:
    image:
      repository: myrep
  scheduler:
    image:
      tag: v0.0.0

metricsOperator:
  enabled: false
  imagePullSecrets: []
