apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# import the default deployment as the base
resources:
  - ../../operator/config/default
  - ../../klt-cert-manager/config/default
  - ../../metrics-operator/config/default
  - ../../scheduler/manifests/install

# replace the default namespace with {{ include "chart.namespace" . }}
# .Release.Namespace has not been used so that a custom _helpers.tpl file can maintain the expected behaviour of
# helm install -n
patches:
  - patch: |
      - op: add
        path: '/webhooks/0/namespaceSelector/matchExpressions/-'
        value:
          key: kubernetes.io/metadata.name
          operator: "NotIn"
          values:
            - '{{ .Release.Namespace }}'
    target:
      kind: MutatingWebhookConfiguration
      name: "(mutating-webhook-configuration)"

