name: "Deploy Keptn Lifecycle Toolkit on GH cluster"
description: "Creates a Kind cluster and deploys Keptn Lifecycle Toolkit"
inputs:
   cert-manager-version:
     required: true
     description: "Version of cert-manager that should be deployed"
runs:
  using: "composite"
  steps:
  - name: Set up Go 1.x
    uses: actions/setup-go@v3
    with:
      go-version: ${{ env.GO_VERSION }}
      cache: true
      cache-dependency-path: '**/go.sum'

  - name: Download manifests
    uses: actions/download-artifact@v3
    with:
      path: ~/download/artifacts

  - name: Create k8s Kind Cluster
    uses: helm/kind-action@v1.3.0
  
  - name: Install cert-manager
    shell: bash
    run: |
      kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/${{ inputs.cert-manager-version }}/cert-manager.yaml
      kubectl rollout status deployment cert-manager-cainjector -n cert-manager -w
      kubectl rollout status deployment cert-manager-webhook -n cert-manager -w
      kubectl rollout status deployment cert-manager -n cert-manager -w
    
  - name: Install lifecycle-toolkit
    shell: bash
    run: |
      kubectl apply -f ~/download/artifacts/keptn-lifecycle-operator-manifest
      kubectl apply -f ~/download/artifacts/scheduler-manifest
      kubectl rollout status deployment keptn-scheduler -n keptn-lifecycle-toolkit-system -w
      kubectl rollout status deployment klc-controller-manager -n keptn-lifecycle-toolkit-system -w
