---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: OTEL_COLLECTOR_URL
              value: "{{ .Values.otelCollector.url }}"
            - name: KEPTN_APP_CONTROLLER_LOG_LEVEL
              value: "{{ .Values.operator.keptnappController.logLevel }}"
            - name: KEPTN_APP_VERSION_CONTROLLER_LOG_LEVEL
              value: "{{ .Values.operator.keptnappversionController.logLevel }}"
            - name: KEPTN_EVALUATION_CONTROLLER_LOG_LEVEL
              value: "{{ .Values.operator.keptnevaluationController.logLevel }}"
            - name: KEPTN_TASK_CONTROLLER_LOG_LEVEL
              value: "{{ .Values.operator.keptntaskController.logLevel }}"
            - name: KEPTN_TASK_DEFINITION_CONTROLLER_LOG_LEVEL
              value: "{{ .Values.operator.keptntaskdefinitionController.logLevel }}"
            - name: KEPTN_WORKLOAD_CONTROLLER_LOG_LEVEL
              value: "{{ .Values.operator.keptnworkloadController.logLevel }}"
            - name: KEPTN_WORKLOAD_INSTANCE_CONTROLLER_LOG_LEVEL
              value: "{{ .Values.operator.keptnworkloadinstanceController.logLevel }}"
            - name: METRICS_CONTROLLER_LOG_LEVEL
              value: "{{ .Values.operator.metricsController.logLevel }}"
            - name: OPTIONS_CONTROLLER_LOG_LEVEL
              value: "{{ .Values.operator.optionsController.logLevel }}"



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
#            - name: NEW_ENV_VAR
#              value: "{{ .Values.myNewEnvVar }}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keptn-scheduler
  namespace: keptn-lifecycle-toolkit-system
spec:
  template:
    spec:
      containers:
        - name: keptn-scheduler
          env:
            - name: OTEL_COLLECTOR_URL
              value: "{{ .Values.otelCollector.url }}"

