apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: cert-manager
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: cert-manager-metrics-service
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: cert-manager
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/managed-by: kustomize
  name: cert-manager-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: cert-manager
