apiVersion: metrics.keptn.sh/v1alpha2
kind: KeptnMetricsProvider
metadata:
  name: prometheus
  namespace: podtato-kubectl
spec:
  targetServer: "http://mockserver.keptn-lifecycle-toolkit-system.svc.cluster.local:1080"
