apiVersion: lifecycle.keptn.sh/v1alpha1
kind: KeptnTaskDefinition
metadata:
  name: check-entry-service
  namespace: podtato-kubectl
spec:
  function:
    httpRef:
      url: https://raw.githubusercontent.com/keptn-sandbox/lifecycle-controller/doc/add_dns_function/functions-runtime/samples/ts/dns.ts
    parameters:
      map:
        host: podtato-head-entry.podtato-kubectl.svc.cluster.local
