apiVersion: lifecycle.keptn.sh/v1alpha1
kind: KeptnTaskDefinition
metadata:
  name: post-deployment-hello
spec:
  function:
    inline:
      code: |
        console.log("Post-Deployment Task has been executed");