# permissions for end users to view services.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptncomponents-viewer-role
rules:
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptncompoonents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptncomponents/status
  verbs:
  - get
