# permissions for end users to view events.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptnevent-viewer-role
rules:
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptnevents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptnevents/status
  verbs:
  - get
