# permissions for end users to edit services.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptncomponent-editor-role
rules:
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptncomponents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptncomponents/status
  verbs:
  - get
