---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - watch
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptnapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptnapps/finalizers
  verbs:
  - update
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptnapps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptncomponents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptncomponents/finalizers
  verbs:
  - update
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptncomponents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptnevents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptnevents/finalizers
  verbs:
  - update
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptnevents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - serviceruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - serviceruns/finalizers
  verbs:
  - update
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - serviceruns/status
  verbs:
  - get
  - patch
  - update
