apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: lifecycle-validating-webhook-configuration
  annotations:
{{- if and .Values.global.caInjectionAnnotations (not (empty .Values.global.caInjectionAnnotations)) }}
{{ .Values.global.caInjectionAnnotations | toYaml | nindent 4| trimPrefix "\n"}}
{{- end }}
    {{- include "common.annotations" ( dict "context" . ) }}
  labels:
    keptn.sh/inject-cert: "true"
{{- include "common.labels.standard" ( dict "context" . ) | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: 'lifecycle-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-lifecycle-keptn-sh-v1beta1-keptntaskdefinition
  failurePolicy: Fail
  name: vkeptntaskdefinition.kb.io
  rules:
  - apiGroups:
    - lifecycle.keptn.sh
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - keptntaskdefinitions
  sideEffects: None