## @section OpenTelemetry
otelCollector:
  ## @param otelCollector.url Sets the URL for the open telemetry collector
  url: "otel-collector:4317"

deployment:
  ## @param deployment.imagePullPolicy Sets the image pull policy for kubernetes deployment
  imagePullPolicy: Always

## @section Controller Log level
operator:
  keptnappController:
    logLevel: 0
  keptnappversionController:
    logLevel: 0
  keptnevaluationController:
    logLevel: 0
  keptntaskController:
    logLevel: 0
  keptntaskdefinitionController:
    logLevel: 0
  keptnworkloadController:
    logLevel: 0
  keptnworkloadinstanceController:
    logLevel: 0
  metricsController:
    logLevel: 0
  optionsController:
    logLevel: 0
