apiVersion: metrics.keptn.sh/v1alpha2
kind: KeptnMetricsProvider
metadata:
  name: prometheus
  namespace: podtato-metrics
spec:
  targetServer: "http://prometheus-k8s.monitoring.svc.cluster.local:9090"
---
apiVersion: metrics.keptn.sh/v1alpha2
kind: KeptnMetric
metadata:
  name: cpu-throttling
  namespace: podtato-metrics
spec:
  provider:
    name: prometheus
  query: 'avg(rate(container_cpu_cfs_throttled_seconds_total{container="server", namespace="podtato-metrics"}[1m]))'
  fetchIntervalSeconds: 60
