apiVersion: options.keptn.sh/v1alpha1
kind: KeptnConfig
metadata:
  labels:
    app.kubernetes.io/name: keptnconfig
    app.kubernetes.io/instance: keptnconfig-sample
    app.kubernetes.io/part-of: keptn-lifecycle-toolkit
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: keptn-lifecycle-toolkit
    control-plane: lifecycle-operator
  name: keptnconfig
  namespace: system
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-failed
spec:
  OTelCollectorUrl: 'otel-collector:4317'
  keptnAppCreationRequestTimeoutSeconds: 30
