apiVersion: v1
kind: Service
metadata:
  name: lifecycle-operator-metrics-service
  namespace: system
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 2222
      targetPort: metrics
  selector:
    control-plane: lifecycle-operator
