apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.fullname" . }}-certificate-operator
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kuberentes.io/instance: certificate-operator
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: certificate-operator
    app.kubernetes.io/part-of: keptn-lifecycle-toolkit
  {{- include "chart.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-certificate-operator
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: certificate-operator
    app.kubernetes.io/part-of: keptn-lifecycle-toolkit
    control-plane: certificate-operator
  {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.certificateOperator.replicas }}
  selector:
    matchLabels:
      control-plane: certificate-operator
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: certificate-operator
      {{- include "chart.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - /manager
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LABEL_SELECTOR_KEY
          value: {{ .Values.certificateOperator.manager.env.labelSelectorKey | quote }}
        - name: LABEL_SELECTOR_VALUE
          value: {{ .Values.certificateOperator.manager.env.labelSelectorValue | quote }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.certificateOperator.manager.image.repository }}:{{ .Values.certificateOperator.manager.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.certificateOperator.manager.imagePullPolicy }}
        name: manager
        resources: {{- toYaml .Values.certificateOperator.manager.resources | nindent 10
          }}
        securityContext:
          allowPrivilegeEscalation: {{ .Values.certificateOperator.manager.containerSecurityContext.allowPrivilegeEscalation
            }}
          capabilities: {{- include "tplvalues.render" (dict "value" .Values.certificateOperator.manager.containerSecurityContext.capabilities
            "context" $) | nindent 12 }}
          readOnlyRootFilesystem: {{ .Values.certificateOperator.manager.containerSecurityContext.readOnlyRootFilesystem
            }}
          runAsGroup: {{ .Values.certificateOperator.manager.containerSecurityContext.runAsGroup
            }}
          runAsUser: {{ .Values.certificateOperator.manager.containerSecurityContext.runAsUser
            }}
          seccompProfile: {{- include "tplvalues.render" (dict "value" .Values.certificateOperator.manager.containerSecurityContext.seccompProfile
            "context" $) | nindent 12 }}
        {{- if .Values.certificateOperator.manager.livenessProbe }}
        livenessProbe: {{- include "tplvalues.render" (dict "value" .Values.certificateOperator.manager.livenessProbe "context" $) | nindent 10 }}
         {{- else }}
        livenessProbe:
         httpGet:
           path: /healthz
           port: 8081
         initialDelaySeconds: 15
         periodSeconds: 20
        {{- end }}
        {{- if .Values.certificateOperator.manager.readinessProbe }}
        readinessProbe: {{- include "tplvalues.render" (dict "value" .Values.certificateOperator.manager.readinessProbe "context" $) | nindent 10 }}
         {{- else }}
        readinessProbe:
         httpGet:
           path: /readyz
           port: 8081
         initialDelaySeconds: 5
         periodSeconds: 10
        {{- end }}
      imagePullSecrets: {{ .Values.imagePullSecrets | default list | toJson }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ include "chart.fullname" . }}-certificate-operator
      terminationGracePeriodSeconds: 10
{{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "tplvalues.render" (dict "value" .Values.topologySpreadConstraints "context" $) | nindent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector: {{- include "tplvalues.render" ( dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations: {{- include "tplvalues.render" (dict "value" .Values.tolerations "context" .) | nindent 8 }}
{{- end }}
