namespace: keptn-lifecycle-toolkit-system
resources:
- base/deployment.yaml
- base/rbac.yaml
- base/serviceaccount.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- files:
  - base/scheduler-config.yaml
  name: scheduler-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: scheduler
  newName : ghcr.keptn.sh/keptn/scheduler
  newTag: "0.6.0-next.1"
