apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: {{ .Values.config.schedulerConfigYaml.leaderElection.leaderElect }}
    profiles: {{ toYaml .Values.config.schedulerConfigYaml.profiles | nindent 6 }}