apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
      annotations:
        keptn.sh/workload: waiter
        keptn.sh/version: "0.4"
        keptn.sh/pre-deployment-tasks: pre-deployment-hello
        keptn.sh/post-deployment-tasks: pre-deployment-hello

    spec:
      containers:
      - image: busybox
        name: busybox
        command: ['sh', '-c', 'echo The app is running! && sleep infinity']
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', 'sleep 30']
status: {}
