apiVersion: lifecycle.keptn.sh/v1alpha2
kind: KeptnTaskDefinition
metadata:
  name: pre-deployment-hello
  namespace: klt-test
spec:
  function:
    inline:
      code: |
        console.log("Pre-Deployment Task has been executed");
