apiVersion: lifecycle.keptn.sh/v1alpha2
kind: KeptnEvaluationDefinition
metadata:
  name: my-prometheus-definition
spec:
  objectives:
    - keptnMetricRef:
        name: name1
        namespace: default
      evaluationTarget: ">1000" #string: can only be starting with < or >

