apiVersion: v1
data:
  SECURE_DATA: eyJzbGFja19ob29rIjoiVDczQVNOQjlRL0IwNDJRTkE3VkdYL1pqb0VZNUxnRFpRS2s1ZHE2YnBCQUFBdiIsInRleHQiOiJEZXBsb3llZCBQb2RUYXRvSGVhZCBBcHBsaWNhdGlvbiJ9
kind: Secret
metadata:
  name: slack-notification
  namespace: podtato-kubectl
