apiVersion: lifecycle.keptn.sh/v1alpha1
kind: KeptnTask
metadata:
  name: slack-deployment-notification
spec:
  taskDefinition: slack-notification-inline
  workload: my-workload
  workloadVersion: "1.0"
  app: my-app
  secureParameters:
    secret: slack-notification

