apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-operator-metrics-service
  namespace: {{ .Release.Namespace | quote }}
  labels:
    control-plane: lifecycle-operator
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.operatorMetricsService.type }}
  selector:
    control-plane: lifecycle-operator
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.operatorMetricsService.ports | toYaml | nindent 2 -}}