---
CheckDoctype: false
IgnoreDirectoryMissingTrailingSlash: true
IgnoreDirs:
  - favicons
  - docs/crd-ref/lifecycle/
  - community/
IgnoreURLs:
  - "linkedin.com"
  - "localhost"
  - "twitter.com"
StripQueryString: false
