processor:
  useRawDocstring: true
  ignoreTypes:
    - "(KeptnConfig|KeptnEvaluationDefinition|KeptnMetricsProvider|KeptnEvaluationProvider)Status$"
  ignoreFields:
    - "TypeMeta$"

render:
  kubernetesVersion: 1.24
