processor:
  useRawDocstring: true
  ignoreTypes:
    - "nomatch" # this needs to be in place as a workaround to avoid generation bugs
  ignoreFields:
    - "TypeMeta$"
    - "EmptyStatus$"
render:
  kubernetesVersion: 1.24
