apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  annotations:
    keptn.sh/application: "application12"
    keptn.sh/service: "service-test"
    keptn.sh/version: "1.1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        keptn.sh/application: "application12"
        keptn.sh/service: "service-test"
        keptn.sh/version: "1.1"
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80