apiVersion: lifecycle.keptn.sh/v1alpha2
kind: KeptnEvaluationDefinition
metadata:
  name: my-prometheus-definition2
  namespace: podtato-kubectl
spec:
  source: prometheus
  objectives:
    - name: available-cpus ## this query should fail
      query: "sum(kube_pod_container_resource_limits{resource='cpu'}) - sum(kube_node_status_capacity{resource='cpu'})"
      evaluationTarget: ">1"
    - name: consumed-memory  ## this query should pass
      query: "sum(kube_node_status_capacity{resource='memory'})"
      evaluationTarget: "<1000000000000"

