name: CI
on:
  # always execute docker build when something is pushed to main or a maintenance branch
  push:
    branches:
      - 'main'
      - '[0-9]+.[1-9][0-9]*.x'
  # in addition, execute for pull requests to those branches
  pull_request:
    branches:
      - 'main'
      - '[0-9]+.[1-9][0-9]*.x'
env:
  GO_VERSION: "~1.18"
  CONTROLLER_TOOLS_VERSION: "v0.9.2"

  FUNCTIONS_RUNTIME_SVC_ARTIFACT_PREFIX: "FUNCTIONS_RUNTIME_SVC"
  FUNCTIONS_RUNTIME_SVC_ARTIFACT: "functions-runtime"
  FUNCTIONS_RUNTIME_SVC_FOLDER: "functions-runtime/"
  SHOULD_RUN_FUNCTIONS_RUNTIME_SVC: "false"
  
  LFC_SCHEDULER_SVC_ARTIFACT_PREFIX: "LFC_SCHEDULER_SVC"
  LFC_SCHEDULER_SVC_ARTIFACT: "scheduler"
  LFC_SCHEDULER_SVC_FOLDER: "scheduler/"

  OPERATOR_SVC_ARTIFACT_PREFIX: "OPERATOR_SVC"
  OPERATOR_SVC_ARTIFACT: "keptn-lifecycle-operator"
  OPERATOR_SVC_FOLDER: "operator/"
defaults:
  run:
    shell: bash
jobs:
  prepare_ci_run:
    name: Prepare CI Run
    runs-on: ubuntu-20.04
    outputs:
      # metadata
      BUILD_EVERYTHING: ${{ steps.build_everything.outputs.BUILD_EVERYTHING }}
      GIT_SHA: ${{ steps.extract_branch.outputs.GIT_SHA }}
      BRANCH: ${{ steps.extract_branch.outputs.BRANCH }}
      BRANCH_SLUG: ${{ steps.extract_branch.outputs.BRANCH_SLUG }}
      DATETIME: ${{ steps.get_datetime.outputs.DATETIME }}
      BUILD_TIME: ${{ steps.get_datetime.outputs.BUILD_TIME }}
      BUILD_MATRIX: ${{ steps.check_modified_files.outputs.BUILD_MATRIX }}
      BUILD_MATRIX_EMPTY: ${{ steps.check_modified_files.outputs.BUILD_MATRIX_EMPTY }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed_files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true

      - name: Prepare for build-everything run
        if: (github.event_name == 'push') || (github.event_name == 'workflow_dispatch') || (contains(github.event.pull_request.labels.*.name, 'CI:trigger-build-everything')) || contains(github.event.pull_request.labels.*.name, format('autorelease{0} pending', ':'))
        id: build_everything
        run: |
          BUILD_EVERYTHING=true
          echo "##[set-output name=BUILD_EVERYTHING;]$(echo ${BUILD_EVERYTHING})"

      - name: Prepare artifacts with changes
        id: check_modified_files
        env:
          BUILD_EVERYTHING: ${{ steps.build_everything.outputs.BUILD_EVERYTHING }}
          GITHUB_REF_PROTECTED: ${{ env.GITHUB_REF_PROTECTED }}
        run: |
          ./gh-actions-scripts/prepare_changed_artifacts.sh "${{ steps.changed_files.outputs.all }}"

      - name: Extract branch name
        id: extract_branch
        # see https://github.com/keptn/gh-action-extract-branch-name for details
        uses: keptn/gh-action-extract-branch-name@main

      - name: Get current date and time
        id: get_datetime
        run: |
          DATETIME=$(date +'%Y%m%d%H%M')
          BUILD_TIME=$(date -u "+%F_%T")
          echo "DATETIME=$DATETIME" >> "$GITHUB_OUTPUT"
          echo "BUILD_TIME=$BUILD_TIME" >> "$GITHUB_OUTPUT"

  compile:
    name: Compile
    needs: prepare_ci_run
    if: needs.prepare_ci_run.outputs.BUILD_MATRIX_EMPTY == 'false'
    runs-on: ubuntu-20.04
    env:
      BRANCH: ${{ needs.prepare_ci_run.outputs.BRANCH }}
      DATETIME: ${{ needs.prepare_ci_run.outputs.DATETIME }}
      GIT_SHA: ${{ needs.prepare_ci_run.outputs.GIT_SHA }}
    strategy:
      matrix: ${{ fromJson(needs.prepare_ci_run.outputs.BUILD_MATRIX) }}
    steps:
      - name: Check out code
        if: matrix.config.should-run == 'true'
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        if: matrix.config.should-run == 'true'
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: '${{ matrix.config.working-dir }}go.sum'

      - name: Go fmt
        if: matrix.config.should-run == 'true' && matrix.config.artifact != 'functions-runtime'
        working-directory: ./${{ matrix.config.working-dir }}
        run: |
          go vet ./...

      - name: Go fmt
        if: matrix.config.should-run == 'true' && matrix.config.artifact != 'functions-runtime'
        working-directory: ./${{ matrix.config.working-dir }}
        run: |
          go fmt ./...

      - name: Compile ${{ matrix.config.artifact }}
        if: matrix.config.should-run == 'true'
        working-directory: ./${{ matrix.config.working-dir }}
        run: |
          make build

  test:
    name: Unit Tests
    needs: prepare_ci_run
    if: needs.prepare_ci_run.outputs.BUILD_MATRIX_EMPTY == 'false'
    runs-on: ubuntu-20.04
    strategy:
      matrix: ${{ fromJson(needs.prepare_ci_run.outputs.BUILD_MATRIX) }}
    steps:
      - name: Check out code
        if: matrix.config.should-run == 'true'
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        if: matrix.config.should-run == 'true'
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: '${{ matrix.config.working-dir }}go.sum'

      - name: Test ${{ matrix.config.artifact }}
        if: matrix.config.should-run == 'true'
        working-directory: ./${{ matrix.config.working-dir }}
        run: |
          make test

  build_image:
    name: Build and push Docker Image
    needs: [ prepare_ci_run ]
#    needs: [ prepare_ci_run, compile, test ]
    runs-on: ubuntu-20.04
    permissions:
      packages: write # Needed for pushing images to the registry
    env:
      BRANCH: ${{ needs.prepare_ci_run.outputs.BRANCH }}
      DATETIME: ${{ needs.prepare_ci_run.outputs.DATETIME }}
      BUILD_TIME: ${{ needs.prepare_ci_run.outputs.BUILD_TIME }}
      GIT_SHA: ${{ needs.prepare_ci_run.outputs.GIT_SHA }}
    strategy:
      matrix: ${{ fromJson(needs.prepare_ci_run.outputs.BUILD_MATRIX) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#        with:
#          platforms: linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        if: ( github.actor != 'renovate[bot]' && github.actor != 'dependabot[bot]' ) && ( github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository )
        uses: docker/login-action@v2
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.config.working-dir }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/keptn-sandbox/${{ matrix.config.artifact }}:dev-${{ env.DATETIME }}
          build-args: |
            GIT_HASH=${{ env.GIT_SHA }}
            RELEASE_VERSION=dev-${{ env.DATETIME }}
            BUILD_TIME=dev-${{ env.BUILD_TIME }}
            CONTROLLER_TOOLS_VERSION=${{ env.CONTROLLER_TOOLS_VERSION }}
          builder: ${{ steps.buildx.outputs.name }}
          pull: true
          push: ${{ inputs.should-push-image == 'true' && ( github.actor != 'renovate[bot]' && github.actor != 'dependabot[bot]' ) && ( github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository ) }}
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}

      - name: Install controller-gen
        if: matrix.config.artifact == 'keptn-lifecycle-operator' && ( github.actor != 'renovate[bot]' && github.actor != 'dependabot[bot]' ) && ( github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository )
        working-directory: ./${{ matrix.config.working-dir }}
        run: go install sigs.k8s.io/controller-tools/cmd/controller-gen@$CONTROLLER_TOOLS_VERSION

      - name: Generate release.yaml
        if: matrix.config.artifact != 'functions-runtime' && ( github.actor != 'renovate[bot]' && github.actor != 'dependabot[bot]' ) && ( github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository )
        working-directory: ./${{ matrix.config.working-dir }}
        env:
          TAG: dev-${{ env.DATETIME }}
        run: |
          rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
          cd config/manager && kustomize edit set image image=ghcr.io/keptn-sandbox/${{ matrix.config.artifact }}:$TAG
          kustomize build config/default > config/rendered/release.yaml

      - name: Upload release.yaml
        if: matrix.config.artifact != 'functions-runtime' && ( github.actor != 'renovate[bot]' && github.actor != 'dependabot[bot]' ) && ( github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository )
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.config.artifact }}-manifest
          path: ${{ matrix.config.working-dir }}/config/rendered/release.yaml
