name: Component Tests
on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: false

# Declare default permissions as read only.
permissions: read-all

env:
  GO_VERSION: "~1.20"
defaults:
  run:
    shell: bash
jobs:
  component_tests:
    name: Component Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@6c1fd22b67f7a7c42ad9a45c0f4197434035e429 # pin@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: 'lifecycle-operator/go.sum'
          check-latest: true

      - name: Execute Component Tests
        working-directory: lifecycle-operator
        run: make component-test

      - name: Report code coverage
        uses: codecov/codecov-action@54bcd8715eee62d40e33596ef5e8f0f48dbbccab # pin@v4
        with:
          flags: component-tests
          token: ${{ secrets.CODECOV_TOKEN }}
