name: Component Tests
on:
  workflow_call:
env:
  GO_VERSION: "~1.19"
defaults:
  run:
    shell: bash
jobs:
  component_tests:
    name: Component Tests
    runs-on: ubuntu-22.04
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
        cache-dependency-path: 'operator/go.sum'

    - name: Execute Component Tests
      working-directory: operator
      run: make component-test

    - name: Report code coverage
      uses: codecov/codecov-action@v3
      with:
        flags: component-tests
