name: E2E-Test
on:
  workflow_call:
    inputs:
      runtime_tag:
        description: "Tag for the runner image"
        type: "string"
        required: true

# Declare default permissions as read only.
permissions: read-all

env:
  GO_VERSION: "~1.23"
defaults:
  run:
    shell: bash

jobs:
  run-e2e-test:
    name: Run E2E Tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        config:
          - name: "lifecycle-operator"
            folder: "lifecycle-operator/"
          - name: "scheduler"
            folder: "scheduler/"
    steps:
      - name: Check out code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup cluster
        uses: ./.github/actions/deploy-keptn-on-cluster
        with:
          runtime_tag: ${{ inputs.runtime_tag }}

      - name: Run E2E Tests ${{ matrix.config.name }}
        working-directory: ${{ matrix.config.folder }}
        run: make e2e-test

      - name: Create reports ${{ matrix.config.name }}
        if: always()
        working-directory: ./.github/scripts
        run: ./create-reports-toolkit.sh

      - name: Upload ${{ matrix.config.name }} cluster logs
        if: always()
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: logs-e2e-tests-${{ matrix.config.name }}
          path: .github/scripts/logs
