name: E2E-Test
on:
  workflow_call:
env:
  GO_VERSION: "~1.18"
  CONTROLLER_TOOLS_VERSION: "v0.9.2"
  ENVTEST_K8S_VERSION: "1.24.2"
  SCHEDULER_COMPATIBLE_K8S_VERSION: "v0.24.3"

defaults:
  run:
    shell: bash

jobs:
  run-e2e-test:
    name: Run E2E Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: '**/go.sum'

      - name: Download manifests
        uses: actions/download-artifact@v3
        with:
          path: ~/download/artifacts

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0
  
      - name: Install cert-manager
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.10.0/cert-manager.yaml
          kubectl rollout status deployment cert-manager-cainjector -n cert-manager -w
          kubectl rollout status deployment cert-manager-webhook -n cert-manager -w
          kubectl rollout status deployment cert-manager -n cert-manager -w
    
      - name: Install lifecycle-toolkit
        run: |
          kubectl apply -f ~/download/artifacts/keptn-lifecycle-operator-manifest
          kubectl apply -f ~/download/artifacts/scheduler-manifest
          kubectl rollout status deployment keptn-scheduler -n keptn-lifecycle-toolkit-system -w
          kubectl rollout status deployment klc-controller-manager -n keptn-lifecycle-toolkit-system -w

      - name: Run E2E Tests Scheduler #TODO maybe separate scheduler and operator in 2 pipelines
        working-directory: ./scheduler
        run: make e2e-test

      - name: Run E2E Tests Operator
        working-directory: ./operator
        run: make e2e-test
