name: golangci-lint
on:
  workflow_call:

env:
  # renovate: datasource=github-tags depName=golangci/golangci-lint
  GOLANGCI_LINT_VERSION: "v1.50.1"
  GO_VERSION: "1.19"
jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "keptn-lifecycle-operator"
            folder: "operator"
          - name: "scheduler"
            folder: "scheduler"
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Download golangci-lint
        run: |
          curl -sSfL "https://raw.githubusercontent.com/golangci/golangci-lint/${{ env.GOLANGCI_LINT_VERSION }}/install.sh" | sh -s -- -b $(go env GOPATH)/bin ${{ env.GOLANGCI_LINT_VERSION }}

      - name: golangci-lint
        continue-on-error: true
        working-directory: ${{ matrix.config.folder }}
        run: |
          golangci-lint run --config ../.golangci.yml --path-prefix ${{ matrix.config.folder }} -v > ${{ matrix.config.name }}-linting-report.xml

      - name: Upload linting report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: linting-report-${{ matrix.config.name }}
          path: ./${{ matrix.config.folder }}/${{ matrix.config.name }}-linting-report.xml
