name: HtmlTest

on:
  push:
    branches:
      - 'main'
      - '[0-9]+.[1-9][0-9]*.x'
    paths:
      - 'docs/**'
  pull_request:
    branches:
      - 'main'
      - '[0-9]+.[1-9][0-9]*.x'
    paths:
      - 'docs/**'

# Declare default permissions as read only.
permissions: read-all

jobs:
  htmltest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: true
          fetch-depth: 0

      - name: Cache HTMLTest packages
        uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4
        with:
          path: |
            tmp/.htmltest
          key: htmltest-${{ hashFiles('tmp/.htmltest/refcache.json') }}

      - name: Check HTML
        run: make htmltest
