name: Integration-Test-Lifecycle
on:
  workflow_call:
    inputs:
      runtime_tag:
        description: "Tag for the deno and python runner images"
        type: "string"
        required: true

# Declare default permissions as read only.
permissions: read-all

env:
  GO_VERSION: "~1.21"
defaults:
  run:
    shell: bash

jobs:
  run-integration-test-lifecycle:
    name: Run Chainsaw Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup cluster
        uses: ./.github/actions/deploy-keptn-on-cluster
        with:
          runtime_tag: ${{ inputs.runtime_tag }}
          values_file: values-integration-lifecycle.yaml

      - name: Install and expose Prometheus
        uses: ./.github/actions/deploy-prometheus-on-cluster

      - name: Install Chainsaw
        uses: kyverno/action-install-chainsaw@995cddaee7702e849270b84fa44cdcebe7462da8 # v0.1.9

      - name: Run Integration Tests Lifecycle
        working-directory: .
        run: make integration-test-lifecycle

      - name: Create reports
        if: failure()
        working-directory: ./.github/scripts
        run: ./create-reports-full.sh

      - name: Upload cluster logs
        if: failure()
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
        with:
          name: logs-integration-tests-lifecycle
          path: .github/scripts/logs
