name: Performance Tests
on:
  workflow_call:
env:
  GO_VERSION: "~1.18"
  CERT_MANAGER_VERSION: "v1.10.0"
defaults:
  run:
    shell: bash
jobs:
  performance_tests:
    name: Performance Tests
    runs-on: ubuntu-22.04
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup cluster
      uses: ./.github/actions/deploy-klt-on-cluster
      with:
        cert-manager-version: ${{ env.CERT_MANAGER_VERSION }}

    - name: Execute Performance Tests
      working-directory: operator
      run: |
        make manifests
        make generate
        make envtest
        TEST_USE_EXISTING_CLUSTER=true
        go test ./test/component/... -v -timeout 30m --ginkgo.focus="Feature:Performance"
