name: release

on:
  push:
    branches:
      - main
  workflow_dispatch: # also run workflow when triggered manually

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          token: ${{secrets.GITHUB_TOKEN}}
          default-branch: main

      - name: Checkout
        uses: actions/checkout@v2
        if: ${{ steps.release.outputs.releases_created }}
        with:
          submodules: recursive

      - name: Get the version
        id: get_version
        if: ${{ steps.release.outputs.releases_created }}
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Create image and manifests
        uses: actions/setup-go@v3
        if: ${{ steps.release.outputs.releases_created }}
        with:
          go-version: '1.18'
      - run: |
          cd functions-runtime
          go mod tidy
          make build-and-push-image TAG=${{ steps.get_version.outputs.VERSION }}
          cd ../lfc-scheduler
          go mod tidy
          make build-and-push-image TAG=${{ steps.get_version.outputs.VERSION }}
          make release-manifests TAG=${{ steps.get_version.outputs.VERSION }}
          cd ../operator
          go mod tidy
          make build-and-push-image TAG=${{ steps.get_version.outputs.VERSION }}
          make controller-gen release-manifests TAG=${{ steps.get_version.outputs.VERSION }}
          cd ..
          cat fc-scheduler/config/rendered/release.yaml operator/config/rendered/release.yaml > manifest.yaml
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: manifest.yaml
