name: "Handle stale issues/PRs"

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          days-before-stale: 60
          days-before-close: 7
          exempt-issue-labels: "pinned,security,future,help wanted,integrations,known issue,known-limitation,Epic,area:security"
          exempt-pr-labels: "pinned,security,future,help wanted,integrations,known issue,known-limitation,Epic,area:security"
          exempt-all-milestones: true
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had recent activity. It will be
            closed if no further activity occurs. Thank you for your contributions.
          stale-pr-message: |
            This issue has been automatically marked as stale because it has not had recent activity. It will be
            closed if no further activity occurs. Thank you for your contributions.
  stale1:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/stale@v8
         with:
           days-before-stale: 21
           stale-issue-message: |
             This issue will be unassigned soon if no further activity is seen. If the asignees are active please provide any update.
           include-only-assigned: true
           remove-stale-when-updated: true
           only-issue-labels: 'good first issue'  

  stale2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          days-before-stale: 28
          stale-issue-message: |
            This issue will be labelled 'to be unassigned' in a week because no response has been encountered.
          include-only-assigned: true
          remove-stale-when-updated: true
          only-issue-labels: 'good first issue'
          stale-issue-label: 'to be unassigned'
    
