name: Set PR Labels

on:
  pull_request_target:

# Declare default permissions as read only.
permissions: read-all

jobs:
  set-labels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:
      - name: Update Labels
        uses: actions/labeler@v5
        with:
          sync-labels: true
