name: Set PR Labels

on:
  pull_request_target:

    # Declare default permissions as read only.
permissions: read-all

jobs:
  set-labels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:
      - name: Update Labels
        uses: actions/labeler@83720bce8638d1b5b7b15ae76465522ca7ea2eec # pin@v5
        with:
          sync-labels: true
