name: Validate Helm Chart
on:
  push:
    branches:
      - 'main'
      - '[0-9]+.[1-9][0-9]*.x'
  pull_request:
    branches:
      - 'main'
      - '[0-9]+.[1-9][0-9]*.x'
defaults:
  run:
    shell: bash
jobs:
  check-helm-docs:
    name: Check helm documentation values
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16

      - name: Generate helm charts
        env:
          RELEASE_REGISTRY: ghcr.io/keptn
        run: make helm-package

      - name: Install readme generator
        run: |
          git clone https://github.com/bitnami-labs/readme-generator-for-helm.git
          cd ./readme-generator-for-helm
          npm ci
          npm install --location=global ./
          cd ..

      - name: Check Helm doc up to date
        run: |
          cd ./helm/chart/
          cp ./README.md ./README-old.md
          cat ./values.yaml ./doc.yaml > ./rendered.yaml
          readme-generator --values=./rendered.yaml --readme=./README.md
          if ! cmp --quiet ./README-old.md ./README.md; then
            echo "The Helm values have changes that are not reflected in the readme."
            echo "Please use ./.github/scripts/generate-helm-docs.sh to re-generate the docs."
            echo ""
            echo "=========== Diff ==========="
            diff -u ./README-old.md ./README.md
            exit 1
          else
            echo ""
            echo "Helm values documentation is correct!"
          fi

  helm-generation-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache build tools
        id: cache-build-tools
        uses: actions/cache@v3
        with:
          path: ./bin
          key: build-tools-${{ github.ref_name }}

      - name: Generate helm charts
        env:
          RELEASE_REGISTRY: ghcr.io/keptn
        run: make helm-package

      - name: Compare YAML file changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo ""
            echo "There are no changes in the manifests"
          else
            echo ""
            echo "Helm charts were not re-generated. Please regenerate them using make helm-package RELEASE_REGISTRY=ghcr.io/keptn"
            echo ""
            echo "=========== Diff ==========="
            git diff
            exit 1
          fi
