name: YAML checks

on:
  push:
    branches:
      - 'main'
      - '[0-9]+.[1-9][0-9]*.x'
      - 'epic/*'
    paths:
      - '**.yaml'
      - '**.yml'
      - '.yamllint'
  pull_request:
    branches:
      - 'main'
      - '[0-9]+.[1-9][0-9]*.x'
      - 'epic/*'
    paths:
      - '**.yaml'
      - '**.yml'
      - '.yamllint'

# Declare default permissions as read only.
permissions: read-all

jobs:
  yamllint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Lint YAML files
        run: make yamllint
